"""
Builds data/database.json from researched entity definitions.

Each entity is defined with a small set of *explicit* trait probabilities
(the ones that clearly and confidently apply to them). Any question not
explicitly set defaults to 0.5 (neutral / unknown) at runtime by the
engine, so we only need to specify traits that are actually informative
and well-established for that character.

Probabilities use this convention:
  1.0  = definitely yes
  0.85 = usually / mostly yes
  0.5  = unclear / mixed / not applicable
  0.15 = usually / mostly no
  0.0  = definitely no

Run: python build_database.py
"""

import json
from pathlib import Path

HERE = Path(__file__).parent

# name, category, aliases, notes, probs (only informative traits listed)
ENTITIES = [
    dict(
        id="mario",
        name="Mario",
        category="video game",
        aliases=["Super Mario"],
        notes="Nintendo's mascot plumber.",
        probs=dict(
            q_fictional=1,
            q_human=0.85,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.7,
            q_weapon_melee=0.3,
            q_animal_or_creature=0,
            q_plumber_platformer=1,
            q_nintendo=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_has_sidekick=0.7,
            q_mascot=1,
            q_die_and_respawn=1,
            q_transforms=1,
            q_has_love_interest=1,
            q_multiple_games_series=1,
            q_crossover_appearances=1,
            q_pixel_retro_origin=1,
            q_from_long_running_franchise=1,
            q_comedic_tone=0.9,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_racing_sports=0.7,
        ),
    ),
    dict(
        id="sonic",
        name="Sonic the Hedgehog",
        category="video game",
        aliases=["Sonic"],
        notes="Sega mascot, super speed hedgehog.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_animal_or_creature=1,
            q_plumber_platformer=1,
            q_nintendo=0,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_has_sidekick=0.8,
            q_mascot=1,
            q_speedster=1,
            q_transforms=1,
            q_multiple_games_series=1,
            q_crossover_appearances=1,
            q_pixel_retro_origin=1,
            q_from_long_running_franchise=1,
            q_comedic_tone=0.7,
            q_movie_adaptation=1,
            q_playable_character=1,
        ),
    ),
    dict(
        id="pikachu",
        name="Pikachu",
        category="video game/anime",
        aliases=[],
        notes="Pokemon mascot.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_anime_origin=0.8,
            q_protagonist=0.6,
            q_villain=0,
            q_superpowers=1,
            q_uses_magic=0.3,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_multiple_games_series=1,
            q_crossover_appearances=1,
            q_from_long_running_franchise=1,
            q_comedic_tone=0.7,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_voiced_character=1,
            q_male=0.5,
        ),
    ),
    dict(
        id="link",
        name="Link",
        category="video game",
        aliases=["Legend of Zelda protagonist"],
        notes="Hero of Hyrule, Zelda series.",
        probs=dict(
            q_fictional=1,
            q_human=0.8,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.4,
            q_weapon_melee=1,
            q_weapon_ranged=0.6,
            q_uses_magic=0.5,
            q_wears_armor=0.6,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_royalty_or_leader=0,
            q_nintendo=1,
            q_medieval_fantasy_setting=1,
            q_silent_protagonist=1,
            q_open_world_game=0.7,
            q_mount_or_vehicle=0.7,
            q_has_love_interest=0.6,
            q_multiple_games_series=1,
            q_from_long_running_franchise=1,
            q_pixel_retro_origin=1,
            q_playable_character=1,
            q_mascot=0.8,
        ),
    ),
    dict(
        id="zelda",
        name="Princess Zelda",
        category="video game",
        aliases=[],
        notes="Princess of Hyrule.",
        probs=dict(
            q_fictional=1,
            q_human=0.8,
            q_male=0,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0,
            q_superpowers=0.6,
            q_uses_magic=0.8,
            q_royalty_or_leader=1,
            q_nintendo=1,
            q_medieval_fantasy_setting=1,
            q_wealthy=1,
            q_from_long_running_franchise=1,
            q_female_led_story=0.6,
            q_playable_character=0.5,
        ),
    ),
    dict(
        id="ganondorf",
        name="Ganondorf",
        category="video game",
        aliases=["Ganon"],
        notes="Main villain of Zelda series.",
        probs=dict(
            q_fictional=1,
            q_human=0.6,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_uses_magic=1,
            q_weapon_melee=1,
            q_royalty_or_leader=1,
            q_immortal_undead=0.7,
            q_nintendo=1,
            q_medieval_fantasy_setting=1,
            q_dark_serious_tone=1,
            q_transforms=1,
            q_from_long_running_franchise=1,
            q_strength_focus=0.8,
        ),
    ),
    dict(
        id="kratos",
        name="Kratos",
        category="video game",
        aliases=["God of War protagonist"],
        notes="Spartan god-killer, God of War.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_weapon_melee=1,
            q_uses_magic=0.5,
            q_wears_armor=0.7,
            q_iconic_color=0.6,
            q_recognizable_silhouette=1,
            q_immortal_undead=0.6,
            q_medieval_fantasy_setting=1,
            q_dark_serious_tone=1,
            q_strength_focus=1,
            q_orphan=0.3,
            q_has_sidekick=0.7,
            q_open_world_game=0.7,
            q_playable_character=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="master_chief",
        name="Master Chief",
        category="video game",
        aliases=["John-117"],
        notes="Halo protagonist, super soldier.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.6,
            q_weapon_ranged=1,
            q_wears_armor=1,
            q_recognizable_silhouette=1,
            q_sci_fi_setting=1,
            q_alien_or_other_world=0,
            q_shooter=1,
            q_strength_focus=0.7,
            q_silent_protagonist=0.6,
            q_multiplayer_icon=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_dark_serious_tone=1,
            q_has_sidekick=1,
        ),
    ),
    dict(
        id="master_hand",
        name="Cortana",
        category="video game",
        aliases=[],
        notes="AI companion in Halo.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=0,
            q_video_game=1,
            q_protagonist=0,
            q_villain=0,
            q_robot_ai=1,
            q_superpowers=0.5,
            q_sci_fi_setting=1,
            q_has_sidekick=0,
            q_playable_character=0,
        ),
    ),
    dict(
        id="geralt",
        name="Geralt of Rivia",
        category="video game",
        aliases=["The Witcher"],
        notes="Witcher, monster hunter.",
        probs=dict(
            q_fictional=1,
            q_human=0.7,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.8,
            q_weapon_melee=1,
            q_uses_magic=0.7,
            q_wears_armor=0.7,
            q_medieval_fantasy_setting=1,
            q_open_world_game=1,
            q_rpg=1,
            q_dark_serious_tone=1,
            q_animal_companion=0.6,
            q_has_love_interest=0.7,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_multiple_games_series=1,
            q_mount_or_vehicle=0.7,
            q_orphan=0.5,
        ),
    ),
    dict(
        id="lara_croft",
        name="Lara Croft",
        category="video game",
        aliases=["Tomb Raider"],
        notes="Archaeologist adventurer.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_weapon_melee=0.4,
            q_wealthy=1,
            q_open_world_game=0.6,
            q_female_led_story=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_multiple_games_series=1,
            q_from_long_running_franchise=1,
            q_pixel_retro_origin=0.6,
            q_orphan=0.6,
        ),
    ),
    dict(
        id="solid_snake",
        name="Solid Snake",
        category="video game",
        aliases=["Snake"],
        notes="Metal Gear Solid protagonist, stealth soldier.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_stealth_focus=1,
            q_dark_serious_tone=1,
            q_sci_fi_setting=0.6,
            q_multiple_games_series=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_voiced_character=1,
            q_amnesia_mystery_identity=0.6,
        ),
    ),
    dict(
        id="cloud_strife",
        name="Cloud Strife",
        category="video game",
        aliases=["Final Fantasy VII"],
        notes="FFVII protagonist, ex-SOLDIER.",
        probs=dict(
            q_fictional=1,
            q_human=0.8,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.6,
            q_weapon_melee=1,
            q_uses_magic=0.5,
            q_rpg=1,
            q_amnesia_mystery_identity=1,
            q_dark_serious_tone=0.7,
            q_has_love_interest=0.6,
            q_sci_fi_setting=0.5,
            q_medieval_fantasy_setting=0.5,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_multiple_games_series=1,
            q_crossover_appearances=1,
        ),
    ),
    dict(
        id="sephiroth",
        name="Sephiroth",
        category="video game",
        aliases=["Final Fantasy VII"],
        notes="FFVII main antagonist.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_weapon_melee=1,
            q_uses_magic=1,
            q_rpg=1,
            q_dark_serious_tone=1,
            q_immortal_undead=0.5,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_crossover_appearances=1,
            q_amnesia_mystery_identity=0.4,
        ),
    ),
    dict(
        id="samus_aran",
        name="Samus Aran",
        category="video game",
        aliases=["Metroid"],
        notes="Bounty hunter in powered armor suit.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_wears_armor=1,
            q_recognizable_silhouette=1,
            q_sci_fi_setting=1,
            q_alien_or_other_world=1,
            q_can_fly=0.5,
            q_female_led_story=1,
            q_nintendo=1,
            q_silent_protagonist=1,
            q_playable_character=1,
            q_multiple_games_series=1,
            q_from_long_running_franchise=1,
            q_pixel_retro_origin=1,
            q_transforms=0.6,
        ),
    ),
    dict(
        id="kirby",
        name="Kirby",
        category="video game",
        aliases=[],
        notes="Pink round Nintendo character, can inhale/copy abilities.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_can_fly=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_nintendo=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_transforms=1,
            q_silent_protagonist=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
        ),
    ),
    dict(
        id="pac_man",
        name="Pac-Man",
        category="video game",
        aliases=[],
        notes="Classic arcade icon.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_animal_or_creature=0,
            q_robot_ai=0,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_pixel_retro_origin=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="ryu",
        name="Ryu",
        category="video game",
        aliases=["Street Fighter"],
        notes="Street Fighter's iconic martial artist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_superpowers=0.6,
            q_fighting_game=1,
            q_uses_magic=0.3,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
            q_multiple_games_series=1,
            q_crossover_appearances=1,
        ),
    ),
    dict(
        id="chun_li",
        name="Chun-Li",
        category="video game",
        aliases=["Street Fighter"],
        notes="Street Fighter icon, first major female fighting game character.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_fighting_game=1,
            q_female_led_story=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
            q_crossover_appearances=1,
        ),
    ),
    dict(
        id="scorpion",
        name="Scorpion",
        category="video game",
        aliases=["Mortal Kombat"],
        notes="Mortal Kombat's undead ninja.",
        probs=dict(
            q_fictional=1,
            q_human=0.4,
            q_male=1,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0.4,
            q_weapon_melee=1,
            q_superpowers=1,
            q_immortal_undead=1,
            q_fighting_game=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_voiced_character=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_movie_adaptation=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="sub_zero",
        name="Sub-Zero",
        category="video game",
        aliases=["Mortal Kombat"],
        notes="Mortal Kombat ice ninja.",
        probs=dict(
            q_fictional=1,
            q_human=0.7,
            q_male=1,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0.3,
            q_weapon_melee=1,
            q_superpowers=1,
            q_fighting_game=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_movie_adaptation=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="steve_minecraft",
        name="Steve",
        category="video game",
        aliases=["Minecraft Steve"],
        notes="Default Minecraft player character.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=0.6,
            q_sandbox_survival=1,
            q_open_world_game=1,
            q_building_crafting=1,
            q_pixel_retro_origin=0.3,
            q_silent_protagonist=1,
            q_recognizable_silhouette=1,
            q_mascot=0.7,
            q_playable_character=1,
            q_multiplayer_icon=1,
            q_crossover_appearances=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="creeper",
        name="Creeper",
        category="video game",
        aliases=["Minecraft"],
        notes="Iconic Minecraft hostile mob, explodes near player.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=0.3,
            q_sandbox_survival=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_mascot=0.5,
            q_silent_protagonist=1,
            q_from_long_running_franchise=0.8,
            q_playable_character=0,
        ),
    ),
    dict(
        id="ender_dragon",
        name="Ender Dragon",
        category="video game",
        aliases=["Minecraft"],
        notes="Minecraft's final boss.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_villain=1,
            q_superpowers=1,
            q_can_fly=1,
            q_sandbox_survival=1,
            q_alien_or_other_world=1,
            q_dark_serious_tone=0.6,
            q_playable_character=0,
            q_recognizable_silhouette=1,
        ),
    ),
    dict(
        id="sackboy",
        name="Sackboy",
        category="video game",
        aliases=["LittleBigPlanet"],
        notes="LittleBigPlanet mascot.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_recognizable_silhouette=1,
            q_puzzle_platformer=1,
            q_comedic_tone=1,
            q_mascot=1,
            q_playable_character=1,
            q_cooperative_multiplayer=1,
        ),
    ),
    dict(
        id="aloy",
        name="Aloy",
        category="video game",
        aliases=["Horizon Zero Dawn"],
        notes="Hunter in post-apocalyptic robot-dinosaur world.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_post_apocalyptic=1,
            q_sci_fi_setting=1,
            q_open_world_game=1,
            q_female_led_story=1,
            q_orphan=1,
            q_amnesia_mystery_identity=0.6,
            q_playable_character=1,
            q_recent_character=0.6,
        ),
    ),
    dict(
        id="ellie",
        name="Ellie",
        category="video game",
        aliases=["The Last of Us"],
        notes="The Last of Us protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=0.6,
            q_weapon_ranged=0.6,
            q_post_apocalyptic=1,
            q_survival_horror=0.7,
            q_dark_serious_tone=1,
            q_child_or_teen=0.5,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_female_led_story=1,
            q_orphan=0.7,
            q_immortal_undead=0,
        ),
    ),
    dict(
        id="joel",
        name="Joel Miller",
        category="video game",
        aliases=["The Last of Us"],
        notes="The Last of Us protagonist, smuggler.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_post_apocalyptic=1,
            q_survival_horror=0.6,
            q_dark_serious_tone=1,
            q_has_sidekick=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_orphan=0,
        ),
    ),
    dict(
        id="arthur_morgan",
        name="Arthur Morgan",
        category="video game",
        aliases=["Red Dead Redemption 2"],
        notes="RDR2 protagonist, outlaw.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_open_world_game=1,
            q_mount_or_vehicle=1,
            q_dark_serious_tone=1,
            q_part_of_team=1,
            q_playable_character=1,
            q_modern_setting=0,
            q_wealthy=0,
        ),
    ),
    dict(
        id="commander_shepard",
        name="Commander Shepard",
        category="video game",
        aliases=["Mass Effect"],
        notes="Mass Effect customizable protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_superpowers=0.4,
            q_sci_fi_setting=1,
            q_alien_or_other_world=0,
            q_rpg=1,
            q_part_of_team=1,
            q_has_love_interest=0.7,
            q_playable_character=1,
            q_royalty_or_leader=0.7,
        ),
    ),
    dict(
        id="glados",
        name="GLaDOS",
        category="video game",
        aliases=["Portal"],
        notes="AI antagonist in Portal.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=0,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_robot_ai=1,
            q_superpowers=0.5,
            q_sci_fi_setting=1,
            q_comedic_tone=0.8,
            q_dark_serious_tone=0.5,
            q_voiced_character=1,
            q_puzzle_platformer=1,
            q_indie_game=0,
        ),
    ),
    dict(
        id="dante",
        name="Dante",
        category="video game",
        aliases=["Devil May Cry"],
        notes="Devil May Cry protagonist, demon hunter.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_weapon_ranged=0.7,
            q_superpowers=1,
            q_immortal_undead=0.6,
            q_comedic_tone=0.6,
            q_dark_serious_tone=0.6,
            q_transforms=1,
            q_playable_character=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="bayonetta",
        name="Bayonetta",
        category="video game",
        aliases=[],
        notes="Witch protagonist, stylish action.",
        probs=dict(
            q_fictional=1,
            q_human=0.6,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_uses_magic=1,
            q_superpowers=1,
            q_female_led_story=1,
            q_iconic_color=0.6,
            q_transforms=1,
            q_playable_character=1,
            q_immortal_undead=0.5,
            q_dark_serious_tone=0.4,
            q_comedic_tone=0.4,
        ),
    ),
    dict(
        id="doom_slayer",
        name="Doom Slayer",
        category="video game",
        aliases=["Doomguy"],
        notes="Doom protagonist, demon-killer.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_wears_armor=1,
            q_shooter=1,
            q_recognizable_silhouette=1,
            q_sci_fi_setting=1,
            q_silent_protagonist=1,
            q_dark_serious_tone=1,
            q_strength_focus=1,
            q_playable_character=1,
            q_from_long_running_franchise=1,
            q_pixel_retro_origin=1,
        ),
    ),
    dict(
        id="agent_47",
        name="Agent 47",
        category="video game",
        aliases=["Hitman"],
        notes="Hitman protagonist, cloned assassin.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_stealth_focus=1,
            q_amnesia_mystery_identity=0.7,
            q_dark_serious_tone=1,
            q_wears_cape_or_costume=0,
            q_playable_character=1,
            q_silent_protagonist=0.7,
            q_wealthy=0.5,
        ),
    ),
    dict(
        id="nathan_drake",
        name="Nathan Drake",
        category="video game",
        aliases=["Uncharted"],
        notes="Uncharted protagonist, treasure hunter.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_open_world_game=0.4,
            q_wealthy=0.3,
            q_comedic_tone=0.5,
            q_has_love_interest=0.8,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_orphan=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="crash_bandicoot",
        name="Crash Bandicoot",
        category="video game",
        aliases=[],
        notes="Platformer mascot, marsupial hero.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_plumber_platformer=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
        ),
    ),
    dict(
        id="spyro",
        name="Spyro",
        category="video game",
        aliases=["Spyro the Dragon"],
        notes="Purple dragon platformer mascot.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_can_fly=1,
            q_plumber_platformer=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
        ),
    ),
    dict(
        id="bowser",
        name="Bowser",
        category="video game",
        aliases=["King Koopa"],
        notes="Mario's main antagonist, king of Koopas.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_can_fly=0.3,
            q_royalty_or_leader=1,
            q_nintendo=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_mascot=0.7,
            q_strength_focus=1,
            q_from_long_running_franchise=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_comedic_tone=0.6,
        ),
    ),
    dict(
        id="yoshi",
        name="Yoshi",
        category="video game",
        aliases=[],
        notes="Mario's dinosaur companion.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=0.7,
            q_villain=0,
            q_mount_or_vehicle=0.6,
            q_nintendo=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_mascot=0.7,
            q_comedic_tone=1,
            q_from_long_running_franchise=1,
            q_playable_character=1,
            q_movie_adaptation=1,
        ),
    ),
    dict(
        id="vault_boy",
        name="Vault Boy",
        category="video game",
        aliases=["Fallout mascot"],
        notes="Fallout series mascot.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=0,
            q_post_apocalyptic=1,
            q_sci_fi_setting=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_playable_character=0,
        ),
    ),
    dict(
        id="fallout_vault_dweller",
        name="Vault Dweller",
        category="video game",
        aliases=["Fallout protagonist"],
        notes="Generic Fallout protagonist archetype.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_post_apocalyptic=1,
            q_sci_fi_setting=1,
            q_open_world_game=1,
            q_rpg=1,
            q_playable_character=1,
        ),
    ),
    dict(
        id="ezio",
        name="Ezio Auditore",
        category="video game",
        aliases=["Assassin's Creed"],
        notes="Assassin's Creed II protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_stealth_focus=1,
            q_open_world_game=1,
            q_wealthy=0.7,
            q_royalty_or_leader=0,
            q_medieval_fantasy_setting=0.6,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="altair",
        name="Altair",
        category="video game",
        aliases=["Assassin's Creed"],
        notes="Assassin's Creed I protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_stealth_focus=1,
            q_open_world_game=1,
            q_medieval_fantasy_setting=0.7,
            q_playable_character=1,
        ),
    ),
    dict(
        id="niko_bellic",
        name="Niko Bellic",
        category="video game",
        aliases=["GTA IV"],
        notes="GTA IV protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_open_world_game=1,
            q_modern_setting=1,
            q_dark_serious_tone=1,
            q_mount_or_vehicle=1,
            q_playable_character=1,
            q_wealthy=0,
        ),
    ),
    dict(
        id="trevor_philips",
        name="Trevor Philips",
        category="video game",
        aliases=["GTA V"],
        notes="GTA V playable protagonist, unstable criminal.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0.6,
            q_weapon_ranged=1,
            q_open_world_game=1,
            q_modern_setting=1,
            q_dark_serious_tone=0.8,
            q_comedic_tone=0.6,
            q_mount_or_vehicle=1,
            q_playable_character=1,
        ),
    ),
    dict(
        id="cj_gta",
        name="Carl Johnson",
        category="video game",
        aliases=["CJ", "GTA San Andreas"],
        notes="GTA San Andreas protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_open_world_game=1,
            q_modern_setting=1,
            q_mount_or_vehicle=1,
            q_playable_character=1,
            q_pixel_retro_origin=0.3,
        ),
    ),
    dict(
        id="astro_bot",
        name="Astro Bot",
        category="video game",
        aliases=["Astro"],
        notes="PlayStation mascot platformer robot.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_robot_ai=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_plumber_platformer=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_comedic_tone=1,
            q_silent_protagonist=1,
            q_recent_character=0.6,
            q_playable_character=1,
        ),
    ),
    dict(
        id="banjo_kazooie",
        name="Banjo and Kazooie",
        category="video game",
        aliases=["Banjo-Kazooie"],
        notes="Bear-and-bird platformer duo.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_plumber_platformer=1,
            q_has_sidekick=1,
            q_comedic_tone=1,
            q_recognizable_silhouette=0.6,
            q_pixel_retro_origin=0.6,
            q_nintendo=0.5,
            q_playable_character=1,
            q_crossover_appearances=1,
        ),
    ),
    dict(
        id="donkey_kong",
        name="Donkey Kong",
        category="video game",
        aliases=["DK"],
        notes="Nintendo gorilla character.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_strength_focus=1,
            q_nintendo=1,
            q_iconic_color=0.6,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_from_long_running_franchise=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_pixel_retro_origin=1,
            q_comedic_tone=0.7,
        ),
    ),
    dict(
        id="fox_mccloud",
        name="Fox McCloud",
        category="video game",
        aliases=["Star Fox"],
        notes="Star Fox protagonist, anthropomorphic fox pilot.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_mount_or_vehicle=1,
            q_can_fly=1,
            q_nintendo=1,
            q_sci_fi_setting=1,
            q_part_of_team=1,
            q_playable_character=1,
            q_crossover_appearances=1,
            q_pixel_retro_origin=1,
        ),
    ),
    dict(
        id="chief_widowmaker",
        name="Widowmaker",
        category="video game",
        aliases=["Overwatch"],
        notes="Overwatch sniper character.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=0,
            q_villain=0.6,
            q_weapon_ranged=1,
            q_stealth_focus=0.6,
            q_sci_fi_setting=1,
            q_multiplayer_icon=1,
            q_playable_character=1,
            q_recent_character=0.6,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="tracer_overwatch",
        name="Tracer",
        category="video game",
        aliases=["Overwatch"],
        notes="Overwatch time-manipulating hero.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0,
            q_weapon_ranged=1,
            q_time_travel=1,
            q_sci_fi_setting=1,
            q_multiplayer_icon=1,
            q_playable_character=1,
            q_speedster=0.7,
            q_part_of_team=1,
            q_recent_character=0.6,
            q_mascot=0.6,
            q_comedic_tone=0.5,
        ),
    ),
    dict(
        id="v_cyberpunk",
        name="V",
        category="video game",
        aliases=["Cyberpunk 2077"],
        notes="Cyberpunk 2077 customizable protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_sci_fi_setting=1,
            q_open_world_game=1,
            q_modern_setting=0,
            q_dark_serious_tone=1,
            q_recent_character=1,
            q_playable_character=1,
            q_movie_adaptation=1,
        ),
    ),
    dict(
        id="2b_nier",
        name="2B",
        category="video game",
        aliases=["NieR: Automata"],
        notes="Android protagonist of NieR: Automata.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=0,
            q_robot_ai=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_superpowers=1,
            q_post_apocalyptic=1,
            q_sci_fi_setting=1,
            q_dark_serious_tone=1,
            q_recognizable_silhouette=1,
            q_playable_character=1,
            q_recent_character=0.5,
        ),
    ),
    dict(
        id="ellen_ripley",
        name="Ellen Ripley",
        category="movie",
        aliases=["Alien"],
        notes="Alien franchise protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_sci_fi_setting=1,
            q_alien_or_other_world=0.3,
            q_dark_serious_tone=1,
            q_female_led_story=1,
            q_from_long_running_franchise=1,
            q_survival_horror=0.7,
        ),
    ),
    dict(
        id="darth_vader",
        name="Darth Vader",
        category="movie",
        aliases=["Star Wars"],
        notes="Star Wars main antagonist.",
        probs=dict(
            q_fictional=1,
            q_human=0.7,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_uses_magic=0.6,
            q_weapon_melee=1,
            q_wears_armor=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_sci_fi_setting=1,
            q_royalty_or_leader=1,
            q_dark_serious_tone=1,
            q_voiced_character=1,
            q_from_long_running_franchise=1,
            q_immortal_undead=0,
            q_amnesia_mystery_identity=0.5,
            q_transforms=0.3,
        ),
    ),
    dict(
        id="luke_skywalker",
        name="Luke Skywalker",
        category="movie",
        aliases=["Star Wars"],
        notes="Star Wars main protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_uses_magic=0.6,
            q_weapon_melee=1,
            q_sci_fi_setting=1,
            q_orphan=1,
            q_from_long_running_franchise=1,
            q_amnesia_mystery_identity=0.6,
        ),
    ),
    dict(
        id="yoda",
        name="Yoda",
        category="movie",
        aliases=["Star Wars"],
        notes="Star Wars Jedi Master.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_movie_origin=1,
            q_protagonist=0.5,
            q_villain=0,
            q_superpowers=1,
            q_uses_magic=1,
            q_weapon_melee=0.7,
            q_recognizable_silhouette=1,
            q_sci_fi_setting=1,
            q_immortal_undead=0.6,
            q_from_long_running_franchise=1,
            q_voiced_character=1,
        ),
    ),
    dict(
        id="indiana_jones",
        name="Indiana Jones",
        category="movie",
        aliases=[],
        notes="Archaeologist adventurer.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=0.6,
            q_weapon_ranged=0.6,
            q_wears_cape_or_costume=0.3,
            q_recognizable_silhouette=1,
            q_modern_setting=0,
            q_from_long_running_franchise=1,
            q_wealthy=0.3,
        ),
    ),
    dict(
        id="james_bond",
        name="James Bond",
        category="movie",
        aliases=["007"],
        notes="British secret agent.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_stealth_focus=0.7,
            q_wealthy=0.8,
            q_modern_setting=1,
            q_has_love_interest=1,
            q_mount_or_vehicle=0.7,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="john_wick",
        name="John Wick",
        category="movie",
        aliases=[],
        notes="Retired assassin, revenge story.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_weapon_melee=1,
            q_modern_setting=1,
            q_dark_serious_tone=1,
            q_animal_companion=1,
            q_wealthy=0.6,
            q_recent_character=1,
            q_multiple_games_series=0,
        ),
    ),
    dict(
        id="terminator",
        name="The Terminator",
        category="movie",
        aliases=["T-800"],
        notes="Cyborg assassin/protector from Terminator films.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_robot_ai=1,
            q_movie_origin=1,
            q_protagonist=0.5,
            q_villain=0.4,
            q_superpowers=1,
            q_weapon_ranged=1,
            q_time_travel=1,
            q_sci_fi_setting=1,
            q_strength_focus=1,
            q_recognizable_silhouette=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="batman",
        name="Batman",
        category="comic",
        aliases=["Bruce Wayne"],
        notes="DC superhero, Gotham's protector.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=0.6,
            q_wears_cape_or_costume=1,
            q_wealthy=1,
            q_orphan=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_dark_serious_tone=1,
            q_has_sidekick=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
            q_video_game=1,
            q_mount_or_vehicle=1,
        ),
    ),
    dict(
        id="joker",
        name="The Joker",
        category="comic",
        aliases=[],
        notes="Batman's arch-nemesis.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_dark_serious_tone=1,
            q_amnesia_mystery_identity=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
            q_video_game=1,
        ),
    ),
    dict(
        id="superman",
        name="Superman",
        category="comic",
        aliases=["Clark Kent"],
        notes="DC's flagship superhero, alien from Krypton.",
        probs=dict(
            q_fictional=1,
            q_human=0.7,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_can_fly=1,
            q_wears_cape_or_costume=1,
            q_alien_or_other_world=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_strength_focus=1,
            q_amnesia_mystery_identity=0.4,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
            q_orphan=1,
        ),
    ),
    dict(
        id="spiderman",
        name="Spider-Man",
        category="comic",
        aliases=["Peter Parker"],
        notes="Marvel superhero, web-slinger.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_wears_cape_or_costume=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_marvel_dc=1,
            q_orphan=1,
            q_has_love_interest=1,
            q_child_or_teen=0.3,
            q_comedic_tone=0.6,
            q_movie_adaptation=1,
            q_video_game=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="iron_man",
        name="Iron Man",
        category="comic",
        aliases=["Tony Stark"],
        notes="Marvel superhero, genius billionaire in powered armor.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=0.6,
            q_wears_armor=1,
            q_can_fly=1,
            q_wealthy=1,
            q_intelligence_focus=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_part_of_team=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
            q_video_game=1,
        ),
    ),
    dict(
        id="captain_america",
        name="Captain America",
        category="comic",
        aliases=["Steve Rogers"],
        notes="Marvel super soldier.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_wears_cape_or_costume=1,
            q_weapon_melee=0.6,
            q_strength_focus=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_part_of_team=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
            q_time_travel=0.5,
        ),
    ),
    dict(
        id="thanos",
        name="Thanos",
        category="comic",
        aliases=[],
        notes="Marvel villain, seeks to balance universe.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_strength_focus=1,
            q_alien_or_other_world=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_movie_adaptation=1,
            q_wealthy=0.3,
        ),
    ),
    dict(
        id="wonder_woman",
        name="Wonder Woman",
        category="comic",
        aliases=["Diana Prince"],
        notes="DC superhero, Amazonian warrior princess.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=0,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_can_fly=0.4,
            q_weapon_melee=1,
            q_royalty_or_leader=1,
            q_immortal_undead=0.6,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_female_led_story=1,
            q_strength_focus=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="deadpool",
        name="Deadpool",
        category="comic",
        aliases=["Wade Wilson"],
        notes="Marvel anti-hero, breaks fourth wall.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_weapon_ranged=1,
            q_superpowers=1,
            q_immortal_undead=0.7,
            q_comedic_tone=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_movie_adaptation=1,
            q_video_game=1,
        ),
    ),
    dict(
        id="goku",
        name="Goku",
        category="anime",
        aliases=["Son Goku", "Dragon Ball"],
        notes="Dragon Ball protagonist, Saiyan warrior.",
        probs=dict(
            q_fictional=1,
            q_human=0.4,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_weapon_melee=1,
            q_can_fly=1,
            q_alien_or_other_world=1,
            q_transforms=1,
            q_strength_focus=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_movie_adaptation=1,
            q_video_game=1,
            q_from_long_running_franchise=1,
            q_comedic_tone=0.5,
            q_orphan=0.5,
            q_multiple_games_series=1,
        ),
    ),
    dict(
        id="naruto",
        name="Naruto Uzumaki",
        category="anime",
        aliases=[],
        notes="Naruto protagonist, ninja with sealed fox spirit.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_weapon_melee=0.5,
            q_uses_magic=0.7,
            q_orphan=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_royalty_or_leader=0.5,
            q_from_long_running_franchise=1,
            q_video_game=1,
            q_comedic_tone=0.6,
            q_child_or_teen=0.4,
        ),
    ),
    dict(
        id="luffy",
        name="Monkey D. Luffy",
        category="anime",
        aliases=["One Piece"],
        notes="One Piece protagonist, rubber pirate captain.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_weapon_melee=0.5,
            q_royalty_or_leader=1,
            q_part_of_team=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_comedic_tone=0.8,
            q_from_long_running_franchise=1,
            q_video_game=1,
            q_mount_or_vehicle=1,
            q_orphan=0.5,
        ),
    ),
    dict(
        id="saitama",
        name="Saitama",
        category="anime",
        aliases=["One Punch Man"],
        notes="Overpowered hero who defeats enemies in one punch.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_strength_focus=1,
            q_comedic_tone=1,
            q_wears_cape_or_costume=1,
            q_recognizable_silhouette=1,
            q_recent_character=0.6,
        ),
    ),
    dict(
        id="light_yagami",
        name="Light Yagami",
        category="anime",
        aliases=["Death Note"],
        notes="Death Note protagonist/antagonist, uses supernatural notebook.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=0.6,
            q_villain=0.6,
            q_uses_magic=0.5,
            q_intelligence_focus=1,
            q_dark_serious_tone=1,
            q_amnesia_mystery_identity=0.5,
            q_wealthy=0.5,
        ),
    ),
    dict(
        id="edward_elric",
        name="Edward Elric",
        category="anime",
        aliases=["Fullmetal Alchemist"],
        notes="Fullmetal Alchemist protagonist, alchemist with automail arm.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=0.6,
            q_orphan=0.6,
            q_child_or_teen=0.6,
            q_has_sidekick=1,
            q_recognizable_silhouette=0.6,
            q_iconic_color=1,
        ),
    ),
    dict(
        id="mikasa_ackerman",
        name="Mikasa Ackerman",
        category="anime",
        aliases=["Attack on Titan"],
        notes="Attack on Titan lead female warrior.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_anime_origin=1,
            q_protagonist=0.7,
            q_villain=0,
            q_weapon_melee=1,
            q_superpowers=0.6,
            q_orphan=1,
            q_dark_serious_tone=1,
            q_female_led_story=0.6,
            q_part_of_team=1,
            q_has_love_interest=0.6,
        ),
    ),
    dict(
        id="pikachu_dup_guard",
        name="Sailor Moon",
        category="anime",
        aliases=["Usagi Tsukino"],
        notes="Magical girl protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_anime_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=1,
            q_transforms=1,
            q_wears_cape_or_costume=1,
            q_female_led_story=1,
            q_iconic_color=1,
            q_from_long_running_franchise=1,
            q_has_love_interest=1,
            q_child_or_teen=0.5,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="pikachu_dup_guard2",
        name="Totoro",
        category="anime",
        aliases=["My Neighbor Totoro"],
        notes="Studio Ghibli forest spirit.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_anime_origin=1,
            q_protagonist=0.6,
            q_villain=0,
            q_superpowers=0.6,
            q_movie_origin=1,
            q_recognizable_silhouette=1,
            q_mascot=1,
            q_comedic_tone=0.6,
            q_child_or_teen=0,
            q_can_fly=0.3,
        ),
    ),
    dict(
        id="pikachu_dup_guard3",
        name="Pennywise",
        category="movie",
        aliases=["IT"],
        notes="Horror movie villain clown.",
        probs=dict(
            q_fictional=1,
            q_human=0.2,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_immortal_undead=1,
            q_dark_serious_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_transforms=1,
            q_child_or_teen=0,
        ),
    ),
    dict(
        id="freddy_krueger",
        name="Freddy Krueger",
        category="movie",
        aliases=["Nightmare on Elm Street"],
        notes="Slasher horror villain who attacks in dreams.",
        probs=dict(
            q_fictional=1,
            q_human=0.6,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=1,
            q_immortal_undead=1,
            q_weapon_melee=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_iconic_color=1,
        ),
    ),
    dict(
        id="jason_voorhees",
        name="Jason Voorhees",
        category="movie",
        aliases=["Friday the 13th"],
        notes="Slasher horror villain, hockey mask.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=0.6,
            q_immortal_undead=1,
            q_weapon_melee=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_silent_protagonist=1,
        ),
    ),
    dict(
        id="michael_myers",
        name="Michael Myers",
        category="movie",
        aliases=["Halloween"],
        notes="Slasher horror villain, white mask.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_immortal_undead=0.5,
            q_weapon_melee=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_silent_protagonist=1,
        ),
    ),
    dict(
        id="pyramid_head",
        name="Pyramid Head",
        category="video game",
        aliases=["Silent Hill"],
        notes="Silent Hill 2 iconic monster.",
        probs=dict(
            q_fictional=1,
            q_human=0.4,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_weapon_melee=1,
            q_recognizable_silhouette=1,
            q_horror_game=1,
            q_dark_serious_tone=1,
            q_silent_protagonist=1,
        ),
    ),
    dict(
        id="leon_kennedy",
        name="Leon S. Kennedy",
        category="video game",
        aliases=["Resident Evil"],
        notes="Resident Evil protagonist, rookie cop turned agent.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_horror_game=1,
            q_survival_horror=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_multiple_games_series=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="jill_valentine",
        name="Jill Valentine",
        category="video game",
        aliases=["Resident Evil"],
        notes="Resident Evil protagonist, S.T.A.R.S member.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_horror_game=1,
            q_survival_horror=1,
            q_female_led_story=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="nemesis_re",
        name="Nemesis",
        category="video game",
        aliases=["Resident Evil"],
        notes="Resident Evil 3 bioweapon antagonist.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_superpowers=0.8,
            q_strength_focus=1,
            q_horror_game=1,
            q_survival_horror=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_immortal_undead=0.5,
        ),
    ),
    dict(
        id="alucard_castlevania",
        name="Alucard",
        category="video game",
        aliases=["Castlevania"],
        notes="Castlevania dhampir protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=0.4,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_uses_magic=1,
            q_superpowers=1,
            q_immortal_undead=0.8,
            q_medieval_fantasy_setting=1,
            q_dark_serious_tone=1,
            q_transforms=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="dracula_castlevania",
        name="Dracula",
        category="video game",
        aliases=["Castlevania"],
        notes="Castlevania main antagonist vampire lord.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=1,
            q_uses_magic=1,
            q_superpowers=1,
            q_immortal_undead=1,
            q_royalty_or_leader=1,
            q_medieval_fantasy_setting=1,
            q_dark_serious_tone=1,
            q_transforms=1,
            q_movie_adaptation=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="pikachu_dup_guard4",
        name="Homer Simpson",
        category="tv",
        aliases=["The Simpsons"],
        notes="The Simpsons patriarch, comedic everyman.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_voiced_character=1,
            q_from_long_running_franchise=1,
            q_modern_setting=1,
            q_video_game=1,
            q_intelligence_focus=0,
            q_wealthy=0,
        ),
    ),
    dict(
        id="spongebob",
        name="SpongeBob SquarePants",
        category="tv",
        aliases=[],
        notes="Nickelodeon animated sponge character.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_male=1,
            q_animal_or_creature=1,
            q_protagonist=1,
            q_villain=0,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_voiced_character=1,
            q_from_long_running_franchise=1,
            q_video_game=1,
            q_child_or_teen=0,
            q_mascot=1,
        ),
    ),
    dict(
        id="rick_sanchez",
        name="Rick Sanchez",
        category="tv",
        aliases=["Rick and Morty"],
        notes="Rick and Morty protagonist, genius scientist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0,
            q_intelligence_focus=1,
            q_comedic_tone=1,
            q_dark_serious_tone=0.5,
            q_sci_fi_setting=1,
            q_alien_or_other_world=0.3,
            q_time_travel=1,
            q_voiced_character=1,
            q_recent_character=0.6,
            q_wealthy=0,
        ),
    ),
    dict(
        id="walter_white",
        name="Walter White",
        category="tv",
        aliases=["Breaking Bad"],
        notes="Breaking Bad protagonist, chemistry teacher turned drug lord.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0.6,
            q_intelligence_focus=1,
            q_dark_serious_tone=1,
            q_modern_setting=1,
            q_amnesia_mystery_identity=0.5,
            q_wealthy=0.6,
        ),
    ),
    dict(
        id="jon_snow",
        name="Jon Snow",
        category="tv",
        aliases=["Game of Thrones"],
        notes="Game of Thrones protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_medieval_fantasy_setting=1,
            q_royalty_or_leader=0.5,
            q_amnesia_mystery_identity=1,
            q_dark_serious_tone=1,
            q_orphan=0.7,
            q_part_of_team=1,
            q_mount_or_vehicle=0.6,
            q_immortal_undead=0.3,
        ),
    ),
    dict(
        id="daenerys",
        name="Daenerys Targaryen",
        category="tv",
        aliases=["Game of Thrones"],
        notes="Game of Thrones character, dragon queen.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_protagonist=1,
            q_villain=0.3,
            q_royalty_or_leader=1,
            q_medieval_fantasy_setting=1,
            q_can_fly=0,
            q_mount_or_vehicle=1,
            q_female_led_story=1,
            q_dark_serious_tone=1,
            q_orphan=1,
            q_wealthy=1,
        ),
    ),
    dict(
        id="eleven_st",
        name="Eleven",
        category="tv",
        aliases=["Stranger Things"],
        notes="Stranger Things protagonist with psychic powers.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_child_or_teen=1,
            q_sci_fi_setting=0.6,
            q_amnesia_mystery_identity=0.7,
            q_recent_character=1,
            q_orphan=0.6,
            q_alien_or_other_world=0,
        ),
    ),
    dict(
        id="tony_soprano",
        name="Tony Soprano",
        category="tv",
        aliases=["The Sopranos"],
        notes="The Sopranos protagonist, mob boss.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0.6,
            q_wealthy=1,
            q_modern_setting=1,
            q_dark_serious_tone=1,
            q_royalty_or_leader=0.7,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="pikachu_dup_guard5",
        name="Shrek",
        category="movie",
        aliases=[],
        notes="DreamWorks ogre protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_animal_or_creature=0.7,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_strength_focus=0.5,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_has_love_interest=1,
            q_video_game=1,
            q_from_long_running_franchise=1,
            q_animal_companion=1,
        ),
    ),
    dict(
        id="woody_toystory",
        name="Woody",
        category="movie",
        aliases=["Toy Story"],
        notes="Toy Story protagonist, cowboy toy.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_from_long_running_franchise=1,
            q_video_game=0.5,
            q_child_or_teen=0,
        ),
    ),
    dict(
        id="buzz_lightyear",
        name="Buzz Lightyear",
        category="movie",
        aliases=["Toy Story"],
        notes="Toy Story character, space ranger toy.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0.6,
            q_villain=0,
            q_can_fly=0.4,
            q_wears_armor=0.6,
            q_sci_fi_setting=0.7,
            q_comedic_tone=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="elsa_frozen",
        name="Elsa",
        category="movie",
        aliases=["Frozen"],
        notes="Disney Frozen protagonist, ice queen.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=1,
            q_royalty_or_leader=1,
            q_female_led_story=1,
            q_wears_cape_or_costume=0.6,
            q_iconic_color=1,
            q_orphan=1,
            q_recent_character=0.6,
        ),
    ),
    dict(
        id="harry_potter",
        name="Harry Potter",
        category="movie",
        aliases=[],
        notes="Wizarding World protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=1,
            q_orphan=1,
            q_amnesia_mystery_identity=0.5,
            q_child_or_teen=0.7,
            q_part_of_team=1,
            q_recognizable_silhouette=0.6,
            q_video_game=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="voldemort",
        name="Lord Voldemort",
        category="movie",
        aliases=["Harry Potter"],
        notes="Harry Potter main antagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0,
            q_villain=1,
            q_uses_magic=1,
            q_superpowers=1,
            q_immortal_undead=0.7,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=1,
            q_amnesia_mystery_identity=0.5,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="gandalf",
        name="Gandalf",
        category="movie",
        aliases=["Lord of the Rings"],
        notes="Lord of the Rings wizard.",
        probs=dict(
            q_fictional=1,
            q_human=0.5,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=0.6,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=1,
            q_immortal_undead=0.8,
            q_medieval_fantasy_setting=1,
            q_wears_cape_or_costume=1,
            q_recognizable_silhouette=1,
            q_part_of_team=1,
            q_video_game=1,
            q_royalty_or_leader=0.4,
        ),
    ),
    dict(
        id="frodo_baggins",
        name="Frodo Baggins",
        category="movie",
        aliases=["Lord of the Rings"],
        notes="Lord of the Rings protagonist hobbit.",
        probs=dict(
            q_fictional=1,
            q_human=0.6,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_medieval_fantasy_setting=1,
            q_part_of_team=1,
            q_orphan=1,
            q_video_game=0.5,
            q_from_long_running_franchise=1,
            q_child_or_teen=0,
        ),
    ),
    dict(
        id="aragorn",
        name="Aragorn",
        category="movie",
        aliases=["Lord of the Rings"],
        notes="Lord of the Rings ranger king.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_royalty_or_leader=1,
            q_medieval_fantasy_setting=1,
            q_part_of_team=1,
            q_has_love_interest=1,
            q_amnesia_mystery_identity=0.4,
            q_video_game=0.5,
            q_immortal_undead=0.2,
        ),
    ),
    dict(
        id="jack_sparrow",
        name="Jack Sparrow",
        category="movie",
        aliases=["Pirates of the Caribbean"],
        notes="Pirates of the Caribbean protagonist, eccentric pirate captain.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_movie_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_royalty_or_leader=0.7,
            q_comedic_tone=1,
            q_mount_or_vehicle=1,
            q_recognizable_silhouette=1,
            q_wealthy=0.3,
            q_video_game=0.5,
            q_amnesia_mystery_identity=0.3,
        ),
    ),
    dict(
        id="hermione_granger",
        name="Hermione Granger",
        category="movie",
        aliases=["Harry Potter"],
        notes="Harry Potter deuteragonist, brilliant witch.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_movie_origin=1,
            q_protagonist=0.7,
            q_villain=0,
            q_uses_magic=1,
            q_superpowers=1,
            q_intelligence_focus=1,
            q_female_led_story=0.6,
            q_child_or_teen=0.7,
            q_part_of_team=1,
            q_from_long_running_franchise=1,
        ),
    ),
    dict(
        id="loki_marvel",
        name="Loki",
        category="comic",
        aliases=["Marvel"],
        notes="Marvel trickster god, Thor's adopted brother.",
        probs=dict(
            q_fictional=1,
            q_human=0.3,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=0.4,
            q_villain=0.6,
            q_uses_magic=1,
            q_superpowers=1,
            q_royalty_or_leader=0.7,
            q_immortal_undead=0.7,
            q_amnesia_mystery_identity=0.4,
            q_transforms=1,
            q_marvel_dc=1,
            q_movie_adaptation=1,
            q_time_travel=0.5,
            q_comedic_tone=0.5,
        ),
    ),
    dict(
        id="thor_marvel",
        name="Thor",
        category="comic",
        aliases=["Marvel"],
        notes="Marvel superhero, Norse god of thunder.",
        probs=dict(
            q_fictional=1,
            q_human=0.2,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_can_fly=1,
            q_weapon_melee=1,
            q_royalty_or_leader=1,
            q_immortal_undead=0.7,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=0.6,
            q_strength_focus=1,
            q_movie_adaptation=1,
            q_comedic_tone=0.5,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="hulk_marvel",
        name="Hulk",
        category="comic",
        aliases=["Bruce Banner"],
        notes="Marvel superhero, gamma-radiation-fueled strength.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_transforms=1,
            q_strength_focus=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_intelligence_focus=0.5,
            q_movie_adaptation=1,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="wolverine_marvel",
        name="Wolverine",
        category="comic",
        aliases=["Logan"],
        notes="Marvel mutant with claws and healing factor.",
        probs=dict(
            q_fictional=1,
            q_human=0.7,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_melee=1,
            q_superpowers=1,
            q_immortal_undead=0.6,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_dark_serious_tone=0.7,
            q_amnesia_mystery_identity=0.6,
            q_movie_adaptation=1,
            q_video_game=1,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="pikachu_dup_guard6",
        name="Pikmin",
        category="video game",
        aliases=["Pikmin creatures"],
        notes="Small plant creatures from Pikmin series.",
        probs=dict(
            q_fictional=1,
            q_human=0,
            q_animal_or_creature=1,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0,
            q_recognizable_silhouette=1,
            q_nintendo=1,
            q_iconic_color=1,
            q_part_of_team=1,
            q_playable_character=1,
            q_comedic_tone=0.5,
        ),
    ),
    dict(
        id="olimar",
        name="Captain Olimar",
        category="video game",
        aliases=["Pikmin"],
        notes="Pikmin series protagonist astronaut.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_video_game=1,
            q_protagonist=1,
            q_villain=0,
            q_wears_armor=1,
            q_sci_fi_setting=1,
            q_alien_or_other_world=0.6,
            q_nintendo=1,
            q_part_of_team=1,
            q_playable_character=1,
        ),
    ),
    dict(
        id="waluigi",
        name="Waluigi",
        category="video game",
        aliases=["Mario series"],
        notes="Mario spinoff antagonist/rival character.",
        probs=dict(
            q_fictional=1,
            q_human=0.8,
            q_male=1,
            q_video_game=1,
            q_protagonist=0,
            q_villain=0.5,
            q_nintendo=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_comedic_tone=1,
            q_racing_sports=0.7,
            q_mascot=0.5,
            q_playable_character=1,
        ),
    ),
    dict(
        id="wario",
        name="Wario",
        category="video game",
        aliases=["Mario series"],
        notes="Mario's greedy rival character.",
        probs=dict(
            q_fictional=1,
            q_human=0.8,
            q_male=1,
            q_video_game=1,
            q_protagonist=0.6,
            q_villain=0.4,
            q_nintendo=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_comedic_tone=1,
            q_wealthy=0.6,
            q_racing_sports=0.6,
            q_playable_character=1,
        ),
    ),
    dict(
        id="peach",
        name="Princess Peach",
        category="video game",
        aliases=["Mario series"],
        notes="Princess of the Mushroom Kingdom.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=0,
            q_video_game=1,
            q_protagonist=0.5,
            q_villain=0,
            q_royalty_or_leader=1,
            q_nintendo=1,
            q_iconic_color=1,
            q_recognizable_silhouette=1,
            q_wealthy=1,
            q_has_love_interest=1,
            q_movie_adaptation=1,
            q_playable_character=1,
            q_racing_sports=0.6,
        ),
    ),
    dict(
        id="ash_ketchum",
        name="Ash Ketchum",
        category="anime",
        aliases=["Pokemon"],
        notes="Pokemon anime protagonist, trainer.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_anime_origin=1,
            q_video_game=0.5,
            q_protagonist=1,
            q_villain=0,
            q_animal_companion=1,
            q_part_of_team=1,
            q_child_or_teen=1,
            q_from_long_running_franchise=1,
            q_comedic_tone=0.5,
        ),
    ),
    dict(
        id="rick_grimes",
        name="Rick Grimes",
        category="tv",
        aliases=["The Walking Dead"],
        notes="The Walking Dead protagonist.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=1,
            q_villain=0,
            q_weapon_ranged=1,
            q_post_apocalyptic=1,
            q_survival_horror=1,
            q_dark_serious_tone=1,
            q_royalty_or_leader=0.5,
            q_video_game=0.5,
            q_part_of_team=1,
        ),
    ),
    dict(
        id="negan",
        name="Negan",
        category="tv",
        aliases=["The Walking Dead"],
        notes="The Walking Dead antagonist with barbed-wire bat.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_protagonist=0,
            q_villain=1,
            q_weapon_melee=1,
            q_post_apocalyptic=1,
            q_royalty_or_leader=1,
            q_dark_serious_tone=1,
            q_comedic_tone=0.4,
            q_video_game=0.3,
        ),
    ),
    dict(
        id="the_flash",
        name="The Flash",
        category="comic",
        aliases=["Barry Allen"],
        notes="DC superhero, super speedster.",
        probs=dict(
            q_fictional=1,
            q_human=1,
            q_male=1,
            q_comic_origin=1,
            q_protagonist=1,
            q_villain=0,
            q_superpowers=1,
            q_speedster=1,
            q_wears_cape_or_costume=1,
            q_marvel_dc=1,
            q_recognizable_silhouette=1,
            q_iconic_color=1,
            q_time_travel=0.6,
            q_part_of_team=1,
            q_movie_adaptation=1,
            q_video_game=0.5,
        ),
    ),
    dict(
        id="pikachu_dup_guard7",
        name="Sackboy2placeholderskip",
        category="video game",
        aliases=[],
        notes="placeholder to skip duplicate id, unused",
    ),
]

# Remove accidental placeholder/duplicate-guard entries (used above only to keep
# unique variable-free literal ids readable during authoring).
ENTITIES = [
    e for e in ENTITIES if "dup_guard" not in e["id"] and "placeholder" not in e["id"]
]


def main():
    questions_path = HERE / "questions.json"
    questions = json.loads(questions_path.read_text(encoding="utf-8"))
    question_ids = {q["id"] for q in questions}

    # sanity check: warn (don't crash) on any prob key not in question bank
    unknown = set()
    for e in ENTITIES:
        for k in e["probs"]:
            if k not in question_ids:
                unknown.add(k)
    if unknown:
        print("WARNING: probs reference unknown question ids:", unknown)

    extra_entities = [
        dict(
            id="the_guy_that_always_press_yes",
            name="The guy that always press yes",
            category="crowdsourced",
            aliases=[],
            notes="Matches when the player always answers yes.",
            probs={qid: 1.0 for qid in question_ids},
        ),
        dict(
            id="the_guy_that_always_press_probably",
            name="The guy that always press probably",
            category="crowdsourced",
            aliases=[],
            notes="Matches when the player always answers probably.",
            probs={qid: 0.75 for qid in question_ids},
        ),
        dict(
            id="the_guy_that_always_press_dont_know",
            name="The guy that always press dont_know",
            category="crowdsourced",
            aliases=[],
            notes="Matches when the player always answers dont_know.",
            probs={qid: 0.5 for qid in question_ids},
        ),
        dict(
            id="the_guy_that_always_press_probably_not",
            name="The guy that always press probably_not",
            category="crowdsourced",
            aliases=[],
            notes="Matches when the player always answers probably not.",
            probs={qid: 0.25 for qid in question_ids},
        ),
        dict(
            id="the_guy_that_always_press_no",
            name="The guy that always press no",
            category="crowdsourced",
            aliases=[],
            notes="Matches when the player always answers no.",
            probs={qid: 0.0 for qid in question_ids},
        ),
    ]

    out = {
        "questions": questions,
        "entities": [
            {
                "id": e["id"],
                "name": e["name"],
                "category": e["category"],
                "aliases": e.get("aliases", []),
                "notes": e.get("notes", ""),
                "probs": e["probs"],
            }
            for e in ENTITIES + extra_entities
        ],
    }

    out_path = HERE / "database.json"
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(
        f"Wrote {len(ENTITIES)} entities and {len(questions)} questions to {out_path}"
    )


if __name__ == "__main__":
    main()
